import {writeFileSync, mkdirSync} from 'node:fs';
const nav=[['index','Home'],['capabilities','Capabilities'],['product','Product'],['about','About us'],['team','Team'],['careers','Careers'],['contact','Contact us']];
const route=page=>page==='index'?'/':`/${page}/`;
const arrow='<span aria-hidden="true">↗</span>';
const link=(href,text,cls='link')=>`<a class="${cls}" href="${route(href)}">${text}${arrow}</a>`;
const label=()=>'';
const header=(page)=>`<a class="skip" href="#main">Skip to content</a><header class="header"><a class="wordmark" href="/" aria-label="SpaceKaur home"><img class="nav-logo" src="/assets/spacekaur-logo.png" alt="SpaceKaur logo"><span>SPACEKAUR</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" aria-label="Main navigation">${nav.map(([p,t])=>`<a href="${route(p)}" ${p===page?'aria-current="page"':''}>${t}${p==='contact'?' ↗':''}</a>`).join('')}</nav></header>`;
const footer=()=>`<footer><div class="footer-top"><div class="footer-company"><p>Autonomous systems for<br>space & aerospace.</p></div><div><a class="footer-email" href="mailto:info@spacekaur.com">info@spacekaur.com ↗</a><a class="footer-phone" href="tel:+919103686947">+91 91036 86947</a><a class="footer-phone" href="tel:+918626097531">+91 86260 97531</a><address class="footer-address">IITM Research Park, 1FA I Floor,<br>Kanagam Road, TTTI Taramani<br>Chennai – 600113, Tamil Nadu, India.</address></div></div><div class="footer-word">SPACEKAUR<span></span></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} SpaceKaur</span><span class="footer-flags"><img src="/assets/flag-india.svg" alt="India" width="27" height="18"><img src="/assets/flag-uk.svg" alt="United Kingdom" width="30" height="18"></span><a href="https://www.linkedin.com/company/spacekaur/" target="_blank" rel="noopener noreferrer">LINKEDIN ↗</a><button class="back-top">BACK TO TOP ↑</button></div></footer>`;
const cta=()=>`<section class="cta section" aria-labelledby="enquiry-heading"><div class="cta-inner"><h2 id="enquiry-heading">Discuss your<br><span>requirements.</span></h2>${link('contact','Talk to our team','cta-link')}</div></section>`;
const caps=[['Modelling & validation','Computational Modeling.','Simulink and Simscape modelling of electromechanical systems, with validation against measured hardware data.','01'],['Servo drives','Servo drive development.','Servo drives for position control applications, developed around the needs of the system.','02'],['Control algorithms','Control system development.','Control system development for autonomous space and aerospace platforms.','03'],['Software & firmware','Embedded software.','Embedded firmware and software for position control, tuning and data analysis.','04'],['Precision actuators','Precision actuation.','High precision actuation, bringing mechanical design, electronics and control together.','05']];
const capRows=()=>caps.map(([t,s,d,n])=>`<details class="cap-row"><summary><span class="mono">${n}</span><h3>${t}</h3><span class="expand" aria-hidden="true">⌄</span></summary><div class="cap-detail${n==='01'?' cap-detail-model':''}"><div class="cap-detail-copy"><h4>${s}</h4><p>${d}</p>${link('contact','Discuss this capability')}</div>${n==='01'?'<figure class="model-thumbnail"><img src="/assets/simulink-model.webp" alt="Simulink model showing the current controller and actuator plant" width="1600" height="900" loading="lazy"></figure>':''}</div></details>`).join('');
const innerHero=(n,k,title,desc)=>`<section class="inner-hero section">${label(n,k)}<h1>${title}</h1><div class="hero-desc"><p>${desc}</p></div></section>`;
const people=[
{name:'Tarandeep Singh',image:'taran.webp',role:'Founder | CEO and Chief Engineer',profile:'https://www.linkedin.com/in/tarandeep-singh-758952231/?isSelfProfile=false'},
{name:'Rohan Nakade',image:'rohan.webp',role:'Co-founder | CTO and CEO',profile:'https://www.linkedin.com/in/rohan-nakade-54485a212/'}
];
const simran={name:'Simran Kaur',profile:'https://www.linkedin.com/in/simran-kaur-engtech-mimeche-58a4b0217/?isSelfProfile=false'};
const mentors=[
{name:'Prof. Murthy Haradanahalli S. N.',image:'murthy.webp',role:'Professor & HoD',department:'Department of Aerospace Engineering',institution:'IIT Madras',profile:'https://ae.iitm.ac.in/~mhsn/',profileLabel:'Faculty profile'},
{name:'Dr. David Kumar',image:'david.webp',role:'Assistant Professor',department:'Department of Aerospace Engineering',institution:'IIT Madras',profile:'https://scholar.google.com/citations?user=wK2QJP4AAAAJ&hl=en',profileLabel:'Google Scholar'}
];
const externalProfile=(p,text=p.name,cls='person-name-link')=>`<a class="${cls}" href="${p.profile.replaceAll('&','&amp;')}" target="_blank" rel="noopener noreferrer">${text}${arrow}</a>`;
const products=[
{id:'servo-drive',name:'Servo Drive',model:'ISHER SKD-I 48/5',image:'isher-drive-cutout.png',alt:'ISHER servo drive circuit board',description:'Servo drive development for position control applications.',tag:'ELECTRONICS / SERVO DRIVE'},
{id:'prodigy',aliases:['software','control'],name:'Software, Control Algorithms & Firmware',model:'PRODIGY',parts:[{name:'Software',model:'PRODIGY S1',description:'Software for position control, tuning and data analysis.'},{name:'Control Algorithms & Firmware',model:'PRODIGY SKD-I 48/5',description:'Control algorithms and embedded firmware, developed together with the hardware.'}],tag:'SOFTWARE / CONTROLS'},
{id:'motor',name:'High Precision Motor',model:'OASIS SKM-D22',image:'oasis-motor-cutout.png',alt:'OASIS precision motor with its mounting plate and wiring',description:'Precision actuation for autonomous space and aerospace systems.',tag:'ACTUATION / PRECISION MOTOR'}
];
const film=(name,alt,cls='')=>`<video class="showcase-video ${cls}" data-showcase-video muted loop playsinline disablepictureinpicture disableremoteplayback preload="none" poster="/assets/${name}-poster.jpg" aria-label="${alt}"><source src="/assets/${name}.mp4" type="video/mp4"></video>`;
const chapter=(content,tone='dark')=>`<div class="scroll-chapter chapter-${tone} can-hold">${content}</div>`;
const productRow=p=>`<article id="${p.id}" class="product-editorial ${p.image?'has-media':'no-media'}">${(p.aliases||[]).map(id=>`<span id="${id}" class="product-anchor" aria-hidden="true"></span>`).join('')}<div class="product-editorial-copy">${p.parts?'<h2>Software,<br>Control Algorithms<br>&amp; Firmware</h2>':`<p class="product-type">${p.name}</p><h2>${p.model.split(' ')[0]}${p.model.includes(' ')?`<span class="product-model-code">${p.model.split(' ').slice(1).join(' ')}</span>`:''}</h2>`}</div><div class="product-detail">${p.parts?`<div class="product-components">${p.parts.map(part=>`<div class="product-component"><h3>${part.name}<span>${part.model}</span></h3><p>${part.description}</p></div>`).join('')}</div>`:`<p>${p.description}</p>`}${link('contact','Enquire about this product','button light')}</div>${p.image?`<div class="product-visual"><img src="/assets/${p.image}" alt="${p.alt}" loading="lazy" width="1536" height="1024"></div>`:''}</article>`;
const incubation=(n='03')=>`<section id="incubation" class="incubation-section section"><div class="incubation-head">${label(n,'OUR ROOTS')}<div><h2>Incubated at<br><span class="outline">IIT Madras.</span></h2></div></div><div class="incubation-collage"><div class="incubation-main">${film('incubation-montage','SpaceKaur control development, IIT Madras aerial footage, Prodigy S.1 software, and a second IIT Madras aerial shot')}</div></div><div class="incubation-foot mono"><span>IIT MADRAS / SPACEKAUR ENGINEERING</span><a href="https://www.youtube.com/watch?v=QDXf4R0fmE0" target="_blank" rel="noopener noreferrer">CAMPUS FILM: IITM RESEARCH PARK ↗</a></div></section>`;
const portrait=p=>`<article class="portrait"><div class="portrait-image"><img src="/assets/${p.image}" alt="${p.name}" loading="lazy" width="800" height="1000"></div><div class="portrait-caption"><h3>${externalProfile(p)}</h3></div>${p.role?`<p class="person-role">${p.role}</p>`:''}</article>`;
const mentorCard=(p,i)=>`<article class="portrait mentor-card"${i===0?' id="mentors"':''}><div class="portrait-image"><img src="/assets/${p.image}" alt="${p.name}" loading="lazy" width="800" height="1000"><span class="portrait-number mono">MENTOR</span></div><div class="portrait-caption"><h3>${externalProfile(p)}</h3></div><p class="mentor-designation">${p.role} · ${p.institution}</p></article>`;
const pages={
index:`<section class="hero"><div class="hero-media"><video id="hero-video" autoplay muted loop playsinline preload="auto" poster="/assets/isa-poster.jpg" aria-label="ISA animation"><source src="/assets/isa-animation.mp4" type="video/mp4"></video></div><div class="hero-shade"></div><div class="hero-content"><h1 class="motto">Proud to build critical<br>subsystems for India's first<br><span>smart ammunition.</span></h1><div class="hero-bottom">${link('capabilities','Explore our capabilities','button light')}</div></div><div class="hero-rail"><a href="#mission">SCROLL TO EXPLORE ↓</a></div></section>
<section id="mission" class="mission section">${label('02','OUR CONVICTION')}<div class="mission-content"><blockquote class="founder-quote reveal"><span class="quote-open" aria-hidden="true">“</span><div class="quote-body"><h2><span class="quote-premise">The question is not if.</span><span class="quote-question">The question is how?</span></h2><p>Because there is always a way.”</p><footer><span class="quote-author">— Taran</span><span class="quote-role">Founder and CEO of SPACEKAUR</span></footer></div></blockquote></div></section>
<section class="motion-feature"><div class="motion-feature-head"><h2>Precision.<br>In motion.</h2><a href="/product/" class="link">View Products ${arrow}</a></div><div class="motion-film">${film('servo-motor-cropped','SpaceKaur OASIS precision motor product film')}</div></section>
${cta()}`,
capabilities:`${innerHero('01','CAPABILITIES','OUR<br><span class="outline">CAPABILITIES.</span>','Precision engineering. From simulation and embedded intelligence to motion control.')}${chapter(`<section class="engineering-strip"><div class="engineering-photo"><img src="/assets/motor-drive.webp" alt="SpaceKaur motor and servo drive assembly" width="1536" height="1024"></div><div class="engineering-strip-copy"><h2>Model.<br>Measure.<br>Refine.</h2><p>Mechanical design, electronics, software and controls, brought together in the hardware.</p></div></section>`,'engineering')}<section class="section capabilities"><div class="section-head">${label('02','WHAT WE DO')}<h2>Engineering services<br>& subsystems.</h2></div><div class="cap-list">${capRows()}</div></section><section class="process section">${label('03','OUR APPROACH')}<h2>Test. Model. Validate.</h2><div class="process-grid">${[['01','Model','Build an understanding of the physics and the system.'],['02','Measure','Capture hardware behaviour through measured data.'],['03','Correlate','Compare the model with the physical response.'],['04','Refine','Use the evidence to inform the next design iteration.']].map(([n,t,d])=>`<article><span class="mono">${n} /</span><h3>${t}</h3><p>${d}</p></article>`).join('')}</div></section>`,
product:`<section class="catalogue-intro section"><div class="catalogue-intro-title"><h1>Build for<br><span class="outline">Control and<br>Precision.</span></h1><div><p>Servo drives, software, control algorithms, firmware and precision motors.</p></div></div></section><section class="product-catalogue" aria-label="Products">${products.map(productRow).join('')}</section>${cta()}`,


about:`${innerHero('01','ABOUT SPACEKAUR','ESTABLISHING<br>PEACE THROUGH<br><span class="outline">STRENGTH.</span>','We build autonomous systems for space and aerospace applications.')}<section class="about-story section"><div class="logo-art"><img src="/assets/spacekaur-logo.png" alt="SpaceKaur rocket emblem" loading="lazy"></div><div>${label('02','OUR STORY')}<h2>About SpaceKaur.</h2><p class="lead">SpaceKaur is building autonomous systems for space and aerospace applications.</p><p>We are incubated at IIT Madras, with a presence in India and the UK.</p><p>We develop physics based models and validate them against measured hardware data. Our work covers control systems, software, electronics and actuation.</p></div></section>${incubation('03')}<section class="location-band section"><h2>India.<br>UK.</h2>${link('team','Meet the team','button')}</section>`,
team:`${innerHero('01','OUR TEAM','OUR <span class="outline">TEAM.</span>','The people building SpaceKaur, supported by mentors from IIT Madras.')}<section class="team-section section" aria-label="SpaceKaur team and mentors"><div class="portrait-grid team-grid">${people.map(portrait).join('')}${mentors.map(mentorCard).join('')}<article class="team-text-profile"><h3>${externalProfile(simran)}</h3><p class="person-role">Founding Team Member</p>${simran.credentials?`<p class="person-credentials">${simran.credentials}</p>`:''}</article></div></section>`,

careers:`<section class="careers-hero section"><div class="careers-title"><h1>Build what<br>comes <span class="outline">next.</span></h1><p>Join the SpaceKaur team.</p></div><div class="careers-apply"><h2>Bring your ambition.</h2><p>Help build autonomous systems for space and aerospace.</p><button class="button" type="button" disabled aria-describedby="careers-status">Join the Team ${arrow}</button><p id="careers-status" class="careers-status">Applications opening soon.</p><a class="careers-email" href="mailto:careers@spacekaur.com">careers@spacekaur.com ${arrow}</a></div></section>`,
contact:`${innerHero('01','CONTACT US','CONTACT<br><span class="outline">US.</span>','For defence programmes, aerospace partnerships and engineering enquiries.')}<section class="contact-section section"><div class="contact-details"><a class="contact-email" href="mailto:info@spacekaur.com">info@spacekaur.com ↗</a><a class="contact-phone" href="tel:+919103686947">+91 91036 86947 ↗</a><a class="contact-phone" href="tel:+918626097531">+91 86260 97531 ↗</a><div class="address"><p>IIT Madras Research Park<br>Chennai, India</p><p>Birmingham, United Kingdom</p><a class="link" href="https://www.linkedin.com/company/spacekaur/" target="_blank" rel="noopener noreferrer">Follow SpaceKaur on LinkedIn ${arrow}</a></div></div><form id="contact-form"><h2>Send an enquiry.</h2><p>Share a little about your programme. This opens a prepared message in your email app.</p><div class="form-grid"><label>Your name<input name="name" autocomplete="name" required placeholder="Full name"></label><label>Work email<input name="email" type="email" autocomplete="email" required placeholder="you@company.com"></label></div><label>Organisation<input name="organisation" autocomplete="organization" required placeholder="Company or institution"></label><label>Area of interest<select name="interest"><option>Strategic partnership</option><option>Product enquiry</option><option>Modelling & validation</option><option>Controls & actuation</option><option>General enquiry</option></select></label><label>Your message<textarea name="message" rows="4" required placeholder="Tell us about your programme or enquiry"></textarea></label><button class="button" type="submit">Prepare email ${arrow}</button><p id="form-status" role="status"></p></form></section>`
};
for(const [page,content] of Object.entries(pages)){
const pacedContent=page==='index'?content.replace(/<section\b[\s\S]*?<\/section>/g,section=>section.includes('class="cta ')?section:chapter(section,section.includes('id="mission"')?'light':'dark')):page==='product'?content.replace(/<article\b[\s\S]*?<\/article>/g,section=>chapter(section,'product')):content;
const title=page==='index'?'Critical Sub Systems':nav.find(([p])=>p===page)[1];
const directory=page==='index'?'dist':`dist/${page}`;
mkdirSync(directory,{recursive:true});
writeFileSync(`${directory}/index.html`,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#111210"><title>SpaceKaur | ${title}</title><meta name="description" content="SpaceKaur builds autonomous systems for space and aerospace. Explore our capabilities, products and team. Incubated at IIT Madras."><link rel="icon" href="/assets/spacekaur-logo.png"><link rel="preload" href="/assets/helvetica-roman.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="/style.css">${page==='product'?'<link rel="stylesheet" href="/product.css">':''}<script src="/app.js" defer></script></head><body class="page-${page}">${header(page)}<main id="main">${pacedContent}</main>${footer()}</body></html>`);
if(page!=='index')writeFileSync(`dist/${page}.html`,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=${route(page)}"><title>SpaceKaur</title></head><body><a href="${route(page)}">Continue to ${title}</a><script>location.replace(${JSON.stringify(route(page))}+location.search+location.hash)</script></body></html>`);
}
writeFileSync('dist/_redirects',nav.map(([page])=>`/${page}.html ${route(page)} 301`).join('\n')+'\n');
console.log('Generated seven pages with clean URLs.');
