import {writeFileSync, mkdirSync} from 'node:fs';
const nav=[['index','Home'],['capabilities','Capabilities'],['product','Product'],['about','About us'],['team','Team'],['contact','Contact us']];
const arrow='<span aria-hidden="true">↗</span>';
const link=(href,text,cls='link')=>`<a class="${cls}" href="${href}.html">${text}${arrow}</a>`;
const label=(n,t)=>`<div class="eyebrow"><span>[ ${n} ]</span> ${t}</div>`;
const header=(page)=>`<a class="skip" href="#main">Skip to content</a><header class="header"><a class="wordmark" href="index.html" aria-label="SpaceKaur home"><span class="brand-cross" aria-hidden="true">✳</span> SPACEKAUR<span class="brand-dot"></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu <span>+</span></button><nav id="navigation" aria-label="Main navigation">${nav.map(([p,t])=>`<a href="${p}.html" ${p===page?'aria-current="page"':''}>${t}${p==='contact'?' ↗':''}</a>`).join('')}</nav></header>`;
const footer=()=>`<footer><div class="footer-top"><p>Engineering autonomy.<br>Building conviction.</p><div><span class="eyebrow">START A CONVERSATION</span><a class="footer-email" href="mailto:info@spacekaur.com">info@spacekaur.com ↗</a><a href="tel:+919103686947">+91 91036 86947</a></div></div><div class="footer-word">SPACEKAUR<span></span></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} SpaceKaur</span><span>CHENNAI, INDIA · BIRMINGHAM, UK</span><a href="https://www.linkedin.com/company/spacekaur/" target="_blank" rel="noopener noreferrer">LINKEDIN ↗</a><button class="back-top">BACK TO TOP ↑</button></div></footer>`;
const cta=()=>`<section class="cta section">${label('NEXT','BUILD WITH SPACEKAUR')}<div><h2>Bring your next<br>mission into focus.</h2>${link('contact','Talk to our team','button light')}</div></section>`;
const caps=[['Modelling & validation','Physics-based models, connected to reality.','Simulink and Simscape modelling of electro-mechanical systems, with validation against measured hardware data.','01'],['Servo drives','Control begins at the drive.','Servo drives for position-control applications, developed around the needs of the system.','02'],['Control algorithms','From system behaviour to precise control.','Control-system development for autonomous space and aerospace platforms.','03'],['Software & firmware','Intelligence across the stack.','Embedded firmware and software for position control, tuning and data analysis.','04'],['Precision actuators','Where decisions become movement.','High-precision actuation, bringing mechanical design, electronics and control together.','05']];
const capRows=()=>caps.map(([t,s,d,n])=>`<details class="cap-row"><summary><span class="mono">${n}</span><h3>${t}</h3><span class="expand" aria-hidden="true">+</span></summary><div class="cap-detail"><h4>${s}</h4><p>${d}</p>${link('contact','Discuss this capability')}</div></details>`).join('');
const innerHero=(n,k,title,desc)=>`<section class="inner-hero section">${label(n,k)}<h1>${title}</h1><div class="hero-desc"><span class="cross" aria-hidden="true">+</span><p>${desc}</p></div></section>`;
const people=[['Taran','taran.webp'],['Rohan','rohan.webp'],['Dr. HSN Murthy','murthy.webp'],['Dr. David','david.webp']];
const portrait=([name,img],i)=>`<article class="portrait reveal"><div class="portrait-image"><img src="assets/${img}" alt="${name}" loading="lazy"><span class="portrait-number mono">0${i+1}</span></div><div class="portrait-caption"><h3>${name}</h3><span aria-hidden="true">↗</span></div></article>`;
const pages={
index:`<section class="hero"><div class="hero-media" data-parallax="0.20"><video id="hero-video" autoplay muted loop playsinline preload="auto" poster="assets/isa-poster.jpg" aria-label="ISA animation"><source src="assets/isa-animation.mp4" type="video/mp4"></video></div><div class="hero-shade"></div><div class="hero-grid" aria-hidden="true"></div><div class="hero-content">${label('01','AUTONOMOUS SYSTEMS. INDEPENDENT THINKING.')}<h1>PRECISION.<br>PURPOSE.<br><span>PEACE.</span></h1><div class="hero-bottom"><p>Proud to be building critical sub-systems<br>for Indian Smart Ammunition.</p>${link('capabilities','Explore our capabilities','button light')}</div></div><div class="hero-rail"><a href="#mission">SCROLL TO EXPLORE ↓</a><span>DESIGNED IN INDIA. BUILT WITH CONVICTION.</span><button id="motion-toggle" aria-label="Pause background video">Ⅱ <span>PAUSE FILM</span></button></div></section>
<div class="credentials"><span>INCUBATED AT <strong>IIT MADRAS</strong></span><span>SPACE & AEROSPACE</span><span>ENGINEERING AUTONOMY <i>↗</i></span></div>
<section id="mission" class="mission section">${label('02','OUR CONVICTION')}<div class="mission-content"><h2 class="reveal">Establishing peace<br>through <span class="outline">strength.</span></h2><div class="split-copy"><span class="cross" aria-hidden="true">+</span><div><p class="lead">We build autonomous systems for space and aerospace applications.</p><p>From the model to the mechanism, our work brings together control, software and precision hardware. Engineering rigour is the thread that runs through it all.</p>${link('about','The SpaceKaur story')}</div></div></div></section>
<section class="product-feature"><div class="feature-image"><img src="assets/isa-poster.jpg" alt="Product One animation still" loading="lazy" data-parallax="0.12"><span class="image-tag mono">PRODUCT ONE / SYSTEM VISUALISATION</span><div class="viewfinder" aria-hidden="true"></div></div><div class="feature-copy">${label('03','IN FOCUS')}<h2>Small systems.<br>Strategic impact.</h2><p>Critical sub-systems sit at the heart of a larger mission. Our focus is the precision that makes the whole system possible.</p>${link('product','Explore the product','button')}</div></section>
<section class="capabilities section"><div class="section-head">${label('04','OUR CAPABILITIES')}<h2 class="reveal">Depth in every<br>discipline.</h2></div><div class="cap-list">${capRows()}</div></section>
<section class="lab-section"><div class="lab-photo"><img src="assets/lab-1.png" alt="Electronics design in the SpaceKaur workspace" loading="lazy" data-parallax="0.10"></div><div class="lab-copy">${label('05','THE ENGINEERING MINDSET')}<h2>Model.<br>Measure.<br>Refine.</h2><p>Ideas take shape in the details. We connect physics-based modelling with measured hardware data to understand how a system behaves.</p>${link('capabilities','Inside our approach')}</div></section>
<section class="team-teaser section">${label('06','THE PEOPLE BEHIND THE PURPOSE')}<div><h2>Built on expertise.<br>Driven by conviction.</h2><p>A team with roots in aerospace engineering and IIT Madras, bringing research and hands-on development together.</p>${link('team','Meet the team','button')}</div></section>${cta()}`,
capabilities:`${innerHero('01','CAPABILITIES','ENGINEERED<br>FROM THE<br><span class="outline">INSIDE OUT.</span>','Five connected disciplines. One systems-level approach to autonomy.')}<section class="wide-media"><img src="assets/lab-1.png" alt="SpaceKaur electronics development" data-parallax="0.12"><span class="image-tag mono">ENGINEERING / CHENNAI, INDIA</span></section><section class="section capabilities"><div class="section-head">${label('02','WHAT WE DO')}<h2>From first principles<br>to working hardware.</h2></div><div class="cap-list">${capRows()}</div></section><section class="process section">${label('03','OUR APPROACH')}<h2>Reality is the<br>reference point.</h2><div class="process-grid">${[['01','Model','Build an understanding of the physics and the system.'],['02','Measure','Capture hardware behaviour through measured data.'],['03','Correlate','Compare the model with the physical response.'],['04','Refine','Use the evidence to inform the next design iteration.']].map(([n,t,d])=>`<article><span class="mono">${n} /</span><h3>${t}</h3><p>${d}</p></article>`).join('')}</div></section>${cta()}`,
product:`${innerHero('01','PRODUCT ONE','PRECISION AT<br>THE <span class="outline">CORE.</span>','Critical sub-systems for Indian Smart Ammunition.')}<section class="product-stage"><video controls playsinline muted loop preload="metadata" poster="assets/isa-poster.jpg" aria-label="Product One animation"><source src="assets/isa-animation.mp4" type="video/mp4"></video><div class="product-stage-label mono"><span>PRODUCT ONE</span><span>SYSTEM VISUALISATION / 01</span></div></section><section class="section product-intro">${label('02','A SYSTEMS PERSPECTIVE')}<div><h2>Every movement<br>begins with control.</h2><p class="lead">Precision actuation. Servo drives. Embedded intelligence.</p><p>SpaceKaur brings these disciplines together in the development of critical aerospace sub-systems. Our work connects the behaviour of the model with the response of the hardware.</p>${link('contact','Discuss your programme','button')}</div></section><section class="product-fields section"><h2>The disciplines<br>behind the system.</h2><div>${[['01','Actuation','High-precision actuators'],['02','Electronics','Servo drives'],['03','Intelligence','Control algorithms and firmware']].map(([n,t,d])=>`<article><span class="mono">${n}</span><h3>${t}</h3><p>${d}</p></article>`).join('')}</div></section>${cta()}`,
about:`${innerHero('01','ABOUT SPACEKAUR','ESTABLISHING<br>PEACE THROUGH<br><span class="outline">STRENGTH.</span>','Autonomous systems for space and aerospace. Built with engineering rigour and a long-term sense of purpose.')}<section class="about-story section"><div class="logo-art"><img src="assets/spacekaur-logo.png" alt="SpaceKaur rocket emblem" loading="lazy"></div><div>${label('02','OUR STORY')}<h2>Independent thinking.<br>Shared purpose.</h2><p class="lead">SpaceKaur is building autonomous systems for space and aerospace applications.</p><p>Incubated at IIT Madras, we bring together a team rooted in aerospace engineering and an approach grounded in physics, testing and evidence.</p><p>Our focus spans the models, control systems, software and hardware that make autonomy possible.</p></div></section><section class="principles section">${label('03','WHAT GUIDES US')}<div><article><span class="mono">01 /</span><h3>Engineering rigour.</h3><p>Understand the physics. Question the assumptions. Return to the measured data.</p></article><article><span class="mono">02 /</span><h3>Systems thinking.</h3><p>Consider each component in the context of the complete platform.</p></article><article><span class="mono">03 /</span><h3>Purposeful progress.</h3><p>Build capability with a clear view of the mission it serves.</p></article></div></section><section class="location-band section"><span class="eyebrow">ROOTED IN RESEARCH. CONNECTED ACROSS BORDERS.</span><h2>Chennai, India.<br>Birmingham, UK.</h2>${link('team','The people behind SpaceKaur','button')}</section>${cta()}`,
team:`${innerHero('01','OUR TEAM','MANY DISCIPLINES.<br>ONE <span class="outline">CONVICTION.</span>','The people bringing engineering, research and a shared purpose to SpaceKaur.')}<section class="team-section section"><div class="portrait-grid">${people.map(portrait).join('')}</div><article class="simran-row"><span class="mono">05 /</span><h3>Simran</h3><span class="eyebrow">SPACEKAUR TEAM</span></article></section><section class="team-note section">${label('02','RESEARCH MEETS PRACTICE')}<h2>Rooted in aerospace.<br>Connected to IIT Madras.</h2><p>Our team brings academic insight and practical engineering into the same conversation, connecting ideas with the work needed to make them real.</p></section>${cta()}`,
contact:`${innerHero('01','CONTACT US','LET’S BUILD<br>WHAT <span class="outline">COMES NEXT.</span>','For defence programmes, aerospace partnerships and engineering enquiries.')}<section class="contact-section section"><div class="contact-details"><span class="eyebrow">DIRECT CONTACT</span><a class="contact-email" href="mailto:info@spacekaur.com">info@spacekaur.com ↗</a><a class="contact-phone" href="tel:+919103686947">+91 91036 86947 ↗</a><div class="address"><span class="eyebrow">FIND US</span><p>IIT Madras Research Park<br>Chennai, India</p><p>Birmingham, United Kingdom</p><a class="link" href="https://www.linkedin.com/company/spacekaur/" target="_blank" rel="noopener noreferrer">Follow SpaceKaur on LinkedIn ${arrow}</a></div></div><form id="contact-form"><h2>Start a conversation.</h2><p>Share a little about your programme. This opens a prepared message in your email app.</p><div class="form-grid"><label>Your name<input name="name" autocomplete="name" required placeholder="Full name"></label><label>Work email<input name="email" type="email" autocomplete="email" required placeholder="you@company.com"></label></div><label>Organisation<input name="organisation" autocomplete="organization" required placeholder="Company or institution"></label><label>Area of interest<select name="interest"><option>Strategic partnership</option><option>Product enquiry</option><option>Modelling & validation</option><option>Controls & actuation</option><option>General enquiry</option></select></label><label>Your message<textarea name="message" rows="4" required placeholder="Tell us about your programme or enquiry"></textarea></label><button class="button" type="submit">Prepare email ${arrow}</button><p id="form-status" role="status"></p></form></section>`
};
for(const [page,content] of Object.entries(pages)){
const title=page==='index'?'Precision. Purpose. Peace.':nav.find(([p])=>p===page)[1];
writeFileSync(`dist/${page}.html`,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#111210"><title>SpaceKaur — ${title}</title><meta name="description" content="SpaceKaur builds autonomous systems for space and aerospace. Explore our capabilities, products and team. Incubated at IIT Madras."><link rel="icon" href="assets/spacekaur-logo.png"><link rel="preload" href="assets/helvetica-roman.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="style.css"><script src="app.js" defer></script></head><body class="page-${page}">${header(page)}<main id="main">${content}</main>${footer()}</body></html>`);
}
console.log('Generated six pages.');
